services:
  web:
    build: .
    volumes:
      - ~/.LNReader:/home/myuser/.LNReader
    environment:
      - HOST_PORT=8000
      - HOST_IP=0.0.0.0
      - MAX_WORKERS=4
      - TIMEOUT=120
    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-80}:${NGINX_PORT:-80}"
    environment:
      - NGINX_PORT=${NGINX_PORT:-80}
    volumes:
      - ./docker/nginx.conf:/etc/nginx/templates/default.conf.template
    command: /bin/sh -c "envsubst '$$NGINX_PORT' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - web
    restart: unless-stopped
