name: build exe
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
    name: Windows, Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: true
    - name: Install dependencies
      run: pdm install
    - name: Build exe
      run: pdm run build
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: LNReaderRS
        path: dist/LNReaderRS.exe
